### ISSUE TITLE
DllNotFoundException: libCoolProp assembly

### ISSUE THREAD

**Issue by liberty293** [portyanikhin/SharpProp#233]
After downloading the package from NuGet, for somereason the libCoolProp dll does not download. Everything works fine in VS, but when I try to run it, I get a DLL not found exception for libCoolProp. I tried grabbing it externally and adding it, but it is still not found.

For context, I am trying to use SharpProp with unity C# .net 2.1

**Comment by portyanikhin** [comment]
Hello, @liberty293!

Just try using a more modern target framework, at least .NET Core 3.1.
On .NET Core 3.1 and higher, everything is fine.

**Comment by liberty293** [comment]
My apologies. I am using .NET _Standard_ 2.1, which is similar to .NET Core 3. However, I am restricted to using .NET Standard 2.1 or .NET Framework. Are you saying the package cannot work with those?

**Comment by portyanikhin** [comment]
I can say for sure (I tested it) that SharpProp works fine with .NET Core 3.1 and higher (3.1, 5.0, 6.0, 7.0 and 8.0), as well as with .NET Framework 4.8.1 and higher.

For example, today I tried to run SharpProp on .NET Core 2.1 and got the error you described above. I can't say exactly why this is, because `libCoolProp.dll` is successfully copied to the `bin` folder. It looks like some features of working with native libraries in .NET Core 2.1. But I don't see any point in making any changes to avoid this, since after replacing the target framework with .NET Core 3.1 everything worked successfully.

I think in your case, you should just upgrade to .NET Core 3.1 or higher.

**Comment by liberty293** [comment]
Very strange. .Net Standard 2.1 supports .Net Core 3.1 (according to https://dotnet.microsoft.com/en-us/platform/dotnet-standard#versions). I have to use either standard 2.1 or framework 4x, but I can switch to .NET framework and see if I can get it running.
